<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rosbag2rawlog</name>
  <version>2.14.15</version>
  <description>CLI tool to transform between ROS1 bags and MRPT rawlogs.</description>

  <maintainer email="markus.bader@tuwien.ac.at">Markus Bader</maintainer>
  <maintainer email="joseluisblancoc@gmail.com">Jose Luis Blanco-Claraco</maintainer>

  <license>BSD</license>
  <url type="website">https://github.com/mrpt/mrpt_ros_bridge</url>

  <!-- Build tool -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- Build dependencies -->
  <depend>roscpp</depend>
  <depend>tf2</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>

  <build_depend>cli11</build_depend>
  <build_depend>cv_bridge</build_depend>
  <build_depend>mrpt_libapps</build_depend>
  <build_depend>mrpt_libros_bridge</build_depend>
  <build_depend>mrpt_msgs</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>rosbag</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>tf2_geometry_msgs</build_depend>
  <build_depend>tf2_msgs</build_depend>
  <build_depend>tf2_ros</build_depend>

  <!-- Runtime dependencies -->
  <exec_depend>cli11</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>mrpt_libapps</exec_depend>
  <exec_depend>mrpt_libros_bridge</exec_depend>
  <exec_depend>mrpt_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>rosbag</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>tf2_geometry_msgs</exec_depend>
  <exec_depend>tf2_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <!-- Documentation -->
  <doc_depend>doxygen</doc_depend>

  <export>
    <build_type>catkin</build_type>
  </export>
</package>
